import Head from 'next/head';
import React, {
  ChangeEvent,
  FunctionComponent,
  SyntheticEvent,
  useEffect,
  useState,
} from 'react';
import Button from './components/Button/Button';
import Container from './components/Container/Container';
import TextInput from './components/TextInput/TextInput';
import Tag from './components/Tag/Tag';
import Text from './components/Text/Text';
import SelectInput from './components/SelectInput/SelectInput';

export const Home: FunctionComponent = () => {
  const [item, setItem] = useState('');
  const [value, setValue] = useState<string>('');
  const [selectInputItem, setSelectInputItem] = useState('');
  const [selectInputValue, setSelectInputValue] = useState<string>('');

  const handleChange = (
    e: ChangeEvent<HTMLInputElement | HTMLSelectElement>
  ) => {
    setValue(e.target.value);
  };

  const handleClick: Function = (e: SyntheticEvent) => {
    e.preventDefault();
    setItem(value);
    setValue('');
  };

  const handleClickSelectInput: Function = (e: SyntheticEvent) => {
    e.preventDefault();
    setSelectInputItem(selectInputValue);
    setSelectInputValue('');
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <main>
        <Container
          variation='md'
          sx={{
            display: 'flex',
            flexDirection: 'column',
            gap: 12,
            maxWidth: 520,
          }}>
          <form style={{ margin: 'auto' }}>
            <TextInput
              value={value}
              label='name'
              onChange={(e) => handleChange(e)}
            />
            <Button
              variation='primary'
              width='w-100'
              data-testid='input-send'
              onClick={(e) => handleClick(e)}>
              Input Send
            </Button>
          </form>
          <div
            style={{
              border: '1px solid #fff8',
              width: '100%',
              padding: 8,
              borderRadius: 8,
              position: 'relative',
            }}>
            <Tag variation='purple md'>{item}</Tag>
          </div>
        </Container>
        <Container
          variation='md'
          sx={{
            display: 'flex',
            flexDirection: 'column',
            gap: 12,
            maxWidth: 520,
          }}>
          <form
            style={{
              margin: 'auto',
              display: 'flex',
              flexDirection: 'column',
              gap: 12,
            }}>
            <SelectInput
              data-testid={'select-teste'}
              disable={false}
              title='Escolha uma opção'
              isLoading={false}
              options={[' ', 'teste', 'teste2']}
              onChange={(e) => setSelectInputValue(e.target.value)}
            />
            <Button
              variation='primary'
              width='w-100'
              data-testid='select-input-send'
              style={{ margin: 10 }}
              onClick={(e) => handleClickSelectInput(e)}>
              Select Input Send
            </Button>
          </form>
          <div
            style={{
              border: '1px solid #fff8',
              width: '100%',
              padding: 8,
              borderRadius: 8,
            }}>
            <Text>{selectInputItem}</Text>
          </div>
        </Container>
      </main>
    </>
  );
};

export default Home;
