import Head from 'next/head';
import React, { FunctionComponent, SyntheticEvent, useEffect } from 'react';
import Button from './components/Button/Button';
import Container from './components/Container/Container';
import { SiAltiumdesigner } from 'react-icons/si';
import TextInput from './components/TextInput/TextInput';
import RadioGroup from './components/RadioGroup/RadioGroup';
import Card from './components/Card/Card';
import wallpaper from '../public/wallpaper.webp';
import Tag from './components/Tag/Tag';
import CardImgBox from './components/CardImgBox/CardImgBox';
import Image from 'next/image';
import CardDescriptionBox from './components/CardDescriptionBox/CardDescriptionBox';
import Title from './components/Title/Title';
import Text from './components/Text/Text';
import SelectInput from './components/SelectInput/SelectInput';
import ToggleButton from './components/ToggleButton/ToggleButton';
import {BsFillSunFill} from 'react-icons/bs';

export const Home: FunctionComponent = () => {
  const handleChange: Function = (e: SyntheticEvent) => {
    const Root = document.querySelector(':root');
    Root?.classList.toggle('light-mode');
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <main>
        <Container variation='sm'>
          <ToggleButton
            id='swt-theme'
            variation='lg'
            onChange={(e) => handleChange(e)}
            content={BsFillSunFill}
          />
          <TextInput
            required={true}
            label='label'
          />
          <RadioGroup
            label='teste'
            options={['one', 'two', 'three']}
          />
          <SelectInput
            onChange={(e) => {
              console.log(e.target);
            }}
            id='select'
            disable={false}
            isLoading={false}
            title='Select one'
            options={[' ', 'teste', 'teste2', 'teste3', 'teste4']}
            sx={{ maxWidth: '140px' }}
          />
        </Container>
        <Container variation='sm'>
          <Button
            variation='primary'
            Icon={<SiAltiumdesigner />}>
            button
          </Button>
          <Button
            variation='outlined'
            Icon={<SiAltiumdesigner />}>
            button
          </Button>
          <Button
            variation='bt-line'
            width='w-100'>
            button
          </Button>
          <Button
            variation='secondary'
            width='w-100'>
            button
          </Button>
        </Container>
        <Container variation='sm'>
          <Card>
            <CardImgBox>
              <Tag
                variation='purple'
                sx={{ top: '-.25em' }}>
                UNVALIABLE
              </Tag>
              <Image
                fill
                src={wallpaper}
                alt=''
              />
            </CardImgBox>
            <CardDescriptionBox>
              <Title variation='h2'>Description</Title>
              <Text>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                Possimus alias aut magni officiis necessitatibus ipsum sit
                repellendus, perspiciatis illum asperiores harum? Est saepe aut,
                asperiores iste sunt consequuntur possimus
                explicabo?sadfasdasdasdasdasdasdasdas Lorem ipsum dolor sit amet
                consectetur adipisicing elit. Ea quis ducimus fugit quas tempore
                maxime molestiae delectus distinctio totam illum eaque ipsam,
                culpa recusandae quam necessitatibus odio. Atque, obcaecati
                nesciunt.
              </Text>
            </CardDescriptionBox>
          </Card>
        </Container>
      </main>
    </>
  );
};

export default Home;
